// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {domain} from '../models';

export function CheckUpdate():Promise<app.UpdateInfo>;

export function DoUpdate(arg1:string):Promise<void>;

export function GetConfig():Promise<domain.Config>;

export function GetServiceStatus(arg1:string):Promise<domain.Status>;

export function InstallService(arg1:string,arg2:Array<domain.InstallFileDTO>):Promise<void>;

export function OpenExplorer(arg1:string):Promise<void>;

export function RestartApp():Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;
