// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['app']['App']['CheckUpdate']();
}

export function DeleteResource(arg1) {
  return window['go']['app']['App']['DeleteResource'](arg1);
}

export function DoUpdate(arg1) {
  return window['go']['app']['App']['DoUpdate'](arg1);
}

export function ExecuteSQLScript(arg1, arg2) {
  return window['go']['app']['App']['ExecuteSQLScript'](arg1, arg2);
}

export function ExportConfig() {
  return window['go']['app']['App']['ExportConfig']();
}

export function GetConfigPath() {
  return window['go']['app']['App']['GetConfigPath']();
}

export function GetDirectories() {
  return window['go']['app']['App']['GetDirectories']();
}

export function GetResourceMetrics(arg1) {
  return window['go']['app']['App']['GetResourceMetrics'](arg1);
}

export function GetServiceStatus(arg1) {
  return window['go']['app']['App']['GetServiceStatus'](arg1);
}

export function GetServices() {
  return window['go']['app']['App']['GetServices']();
}

export function GetSqlConfig() {
  return window['go']['app']['App']['GetSqlConfig']();
}

export function ImportConfig() {
  return window['go']['app']['App']['ImportConfig']();
}

export function Install(arg1, arg2) {
  return window['go']['app']['App']['Install'](arg1, arg2);
}

export function OpenExplorer(arg1) {
  return window['go']['app']['App']['OpenExplorer'](arg1);
}

export function RestartApp() {
  return window['go']['app']['App']['RestartApp']();
}

export function SaveResource(arg1) {
  return window['go']['app']['App']['SaveResource'](arg1);
}

export function StartService(arg1) {
  return window['go']['app']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['app']['App']['StopService'](arg1);
}
